### ISSUE TITLE
Issue 및 PR에 Template이 있으면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by MoonSupport** [BARlSTAS/test-bucket#3]
모카와 같이 .github 디렉토리에 `PULL_REQUEST_TEMPLATE.md` 및 `ISSUE_TEMPLATE template`을 작성하면 반영될 것 같습니다.

reference
https://github.com/mochajs/mocha/tree/master/.github

**Comment by irrationnelle** [comment]
오늘 중으로 *그대로* 번역해서 만들어보도록 하겠습니다~

**Comment by donghoon-song** [comment]
bug report 제가 해도 될까요 @irrationnelle

**Comment by irrationnelle** [comment]
@Donghoon759 그럼그럼요! 같은 작업을 서로 동시에 할 수도 있으니 서로 미리 이야기만 하고 곧바로 작업 진행하면 될 것 같아요 =)

**Comment by donghoon-song** [comment]
@irrationnelle PULL_REQUEST_TEMPLATE.md 작업할게요 :)

**Comment by irrationnelle** [comment]
feature_request.md 번역 작업 중입니다

**Comment by irrationnelle** [comment]
~support-question.md 번역 작업 중입니다~

**Comment by irrationnelle** [comment]
Support Question Issue 의 경우 mocha 리포에서는 별다른 템플릿이 없어서 번역을 안 했어요ㅠ

또 org 에서만 사용하는 리포라면 필요가 없을거라고도 생각했는데 org 와 repo 모두 public 이니 외부에서도 질문을 할 수 있다는 점을 미처 생각하지 못했네요

다른 리포에서 괜찮은 템플릿이 있는지 오늘 밤에 찾아보겠습니다~
